apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: pranavdhopey/myweb:httpd
      ports:
        - name: web
          containerPort: 80
      resources:
        requests:
          memory: 20Mi  #1KiB = 1024bytes  
          cpu: 50m      #1cpu = 1000m cpu
        limits:
          memory: 100Mi
          cpu: 250m
